services:
  scheduler:
    restart: unless-stopped
    image: mcuadros/ofelia:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: daemon --docker
    depends_on:
      - honeygain
      - pawns

  honeygain:
    restart: unless-stopped
    cpus: "0.05"
    mem_reservation: "25M"  # Soft memory reservation
    mem_limit: "50M"  # Hard memory limit
    networks:
      - honeygain
    security_opt:
      - no-new-privileges
      - apparmor:docker-default
    cap_drop:
      - ALL # Drop all capabilities
    cap_add:
      - CAP_MKNOD # Allows the creation of special files using mknod(), such as device files.
      - CAP_CHOWN # Allows changing the ownership of files (i.e., modifying file owner and group).
      - CAP_KILL  # Allows a process to send signals to any process (including processes owned by different users).0
    image: honeygain/honeygain
    command:
      - "-tou-accept"
      - "-email"
      - "$HONEYGAIN_EMAIL"
      - "-pass"
      - "$HONEYGAIN_PASSWORD"
      - "-device"
      - "${RANDOM_DEVICE}"
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.honeygain-restart.schedule: "@every 3h"
      ofelia.job-exec.honeygain-restart.command: "/bin/sh -c 'kill -s TERM 1 && sleep 10 && kill -s KILL 1'"

  pawns:
    restart: unless-stopped
    cpus: "0.05"
    mem_reservation: "25M"  # Soft memory reservation
    mem_limit: "50M"  # Hard memory limit
    networks:
      - pawns
    security_opt:
      - no-new-privileges
      - apparmor:docker-default
    cap_drop:
      - ALL # Drop all capabilities
    cap_add:
      - CAP_MKNOD # Allows the creation of special files using mknod(), such as device files.
      - CAP_CHOWN # Allows changing the ownership of files (i.e., modifying file owner and group).
      - CAP_KILL  # Allows a process to send signals to any process (including processes owned by different users).
    image: iproyal/pawns-cli
    command:
      - "-accept-tos"
      - "-email"
      - "${PAWNS_EMAIL}"
      - "-password"
      - "${PAWNS_PASSWORD}"
      - "-device-name"
      - "${RANDOM_DEVICE}"
      - "-device-id"
      - "${RANDOM_DEVICE}"
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.pawns-restart.schedule: "@every 3h"
      ofelia.job-exec.pawns-restart.command: "/bin/sh -c 'kill -s TERM 1 && sleep 10 && kill -s KILL 1'"

volumes:
  bitping-node-data:

networks:
  honeygain:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"

  pawns:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"
